<a href="https://colab.research.google.com/github/dudipoojitha2008-glitch/AIML-i-HUB-/blob/main/AIML_Sep_2026_Basics_of_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 0

In [2]:
#Strings
#five methods of strings
my_str='peak summer'
print("Capitalised string:",my_str.capitalize())
print("Title:",my_str.title())
print("Does my string start with peak?",my_str.startswith('peak'))
print("what is the index of summer?,A:",my_str.find('summer'))
print("How many times is the letter m repeated?,A:",my_str.count('e'))

Capitalised string: Peak summer
Title: Peak Summer
Does my string start with peak? True
what is the index of summer?,A: 5
How many times is the letter m repeated?,A: 2


In [9]:
#Lists
#five methods of Lists
my_List=[23,'Cloud',2.2,'Sky','blue']
print(my_List)
my_List.append('spread')
print(my_List)
my_List.pop(0)
print(my_List)
my_List.remove(2.2)
print(my_List)
my_List.reverse()
print(my_List)
index1=my_List.index('Sky')
print(index1)
my_List.clear()

[23, 'Cloud', 2.2, 'Sky', 'blue']
[23, 'Cloud', 2.2, 'Sky', 'blue', 'spread']
['Cloud', 2.2, 'Sky', 'blue', 'spread']
['Cloud', 'Sky', 'blue', 'spread']
['spread', 'blue', 'Sky', 'Cloud']
2


In [18]:
#Tuples
#five methods of tuples
my_tuple=((2,3), 'thunder','Sky',2.29,'Dark')
print(my_tuple)
print(my_tuple.count((2,3)))
position=my_tuple.index('Sky')
print(position)
number=(23,49,18,7,2.9)
max_ele=max(number)
print(max_ele)
sorted_numbers=sorted(number)
print(sorted_numbers)
print(len(my_tuple))

((2, 3), 'thunder', 'Sky', 2.29, 'Dark')
1
2
49
[2.9, 7, 18, 23, 49]
5


In [24]:
#Sets
#five methods of sets
my_set={1,2,3}
print(my_set)
my_set.add(4)
print(my_set)
set_A={1,2,3,4,5}
set_B={6,7,8,9,10}
print(set_A.union(set_B))
print(set_A.issubset(set_B))
my_set.update(set_B)
print(my_set)
my_set.intersection_update(set_A)
print(my_set)

{1, 2, 3}
{1, 2, 3, 4}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
False
{1, 2, 3, 4, 6, 7, 8, 9, 10}
{1, 2, 3, 4}


In [36]:
#Dictionaries
#five methods of dictionary
my_dict={"name":"Poojitha","class":"b-tech 2","branch":"CSE"}
print(my_dict)
my_dict.update({"college":"BVRIT"})
print(my_dict)
removed_details=my_dict.pop("class")
print(removed_details)
print(my_dict)
last_item=my_dict.popitem()
print(last_item)
print(my_dict)
dup=my_dict.copy()
print(dup)
print(dup.get("class"))

{'name': 'Poojitha', 'class': 'b-tech 2', 'branch': 'CSE'}
{'name': 'Poojitha', 'class': 'b-tech 2', 'branch': 'CSE', 'college': 'BVRIT'}
b-tech 2
{'name': 'Poojitha', 'branch': 'CSE', 'college': 'BVRIT'}
('college', 'BVRIT')
{'name': 'Poojitha', 'branch': 'CSE'}
{'name': 'Poojitha', 'branch': 'CSE'}
None


Question 1

In [37]:
def string_operation(a:str,b:str):
  a=a[::-1]
  sum=a+b
  return sum
a=input(str("enter a:"))
b=input(str("enter b:"))
ans=string_operation(a,b)
print(ans)


enter a:hello
enter b:world
ollehworld


Question 2

In [38]:
work_hours = [('Abby',100 , 'F'),('Billy',400, 'M'),('Cassie',800,'F'), ('Maggi',600,'F'),('Alex',500,'M'),('Raj',225,'M'),('Penny',920,'F'),('Ben',300,'M')]
highest_tuple = max(work_hours, key=lambda item: item[1])
ans = highest_tuple[1] * 20
print(ans)


18400


Question 3

In [39]:
import numpy as np
r1=np.array([1,1,2,2,3])
r2=np.array([2,2,3,3,4])
r3=np.array([3,3,4,4,5])
r4=np.array([4,4,5,5,6])
r5=np.array([5,5,6,6,7])
matrix=np.vstack((r1, r2, r3, r4, r5))
print(matrix)

[[1 1 2 2 3]
 [2 2 3 3 4]
 [3 3 4 4 5]
 [4 4 5 5 6]
 [5 5 6 6 7]]


In [42]:
A=np.array([[1,2,3,1,2],
            [4,5,6,4,5],
            [7,8,9,7,8],
            [1,2,3,1,2],
            [4,5,6,4,5]])
dot_product=np.dot(A,matrix)
print(dot_product)

[[ 28  28  37  37  46]
 [ 73  73  97  97 121]
 [118 118 157 157 196]
 [ 28  28  37  37  46]
 [ 73  73  97  97 121]]
